### ISSUE TITLE
Failing with WebSocket crash

### ISSUE THREAD

**Issue by saikrishna321** [hkang1/taiko-video#7]
@hkang1 I'm trying to use taiko-video and I it fails with below error 

Runner: **mocha** 
```
"after all" hook: afterAll in "{root}" Error: WebSocket is not open: readyState 3 (CLOSED)
    at sendAfterClose (node_modules/ws/lib/websocket.js:900:17)
    at WebSocket.send (node_modules/ws/lib/websocket.js:402:7)
    at Proxy._enqueueCommand (node_modules/chrome-remote-interface/lib/chrome.js:286:18)
    at /Users/***/Documents/***/node_modules/chrome-remote-interface/lib/chrome.js:88:22
    at new Promise (<anonymous>)
    at Proxy.send (node_modules/chrome-remote-interface/lib/chrome.js:87:20)
    at pause (node_modules/taiko-video/src/index.js:57:23)
    at Object.stop [as stopRecording] (node_modules/taiko-video/src/index.js:65:9)
    at Context.afterAll (src/mochaHooks.js:50:17)
    at processImmediate (node:internal/timers:464:21)

Error: WebSocket is not open: readyState 3 (CLOSED)
    at sendAfterClose (node_modules/ws/lib/websocket.js:900:17)
    at WebSocket.send (node_modules/ws/lib/websocket.js:402:7)
    at Proxy._enqueueCommand (node_modules/chrome-remote-interface/lib/chrome.js:286:18)
    at /Users/****/node_modules/chrome-remote-interface/lib/chrome.js:88:22
    at new Promise (<anonymous>)
    at Proxy.send (node_modules/chrome-remote-interface/lib/chrome.js:87:20)
    at pause (node_modules/taiko-video/src/index.js:57:23)
    at Object.stop [as stopRecording] (node_modules/taiko-video/src/index.js:65:9)
    at Context.afterAll (src/mochaHooks.js:50:17)
    at processImmediate (node:internal/timers:464:21)

```

mochaHooks.js

```
exports.mochaHooks = {
  async beforeAll() {
    await openBrowser({ headless: IS_HEADLESS });
    await goto(BASE_URL);
    await login(USER_NAME, PASSWORD);
    await waitFor(async () => {
      const url = await currentURL();
      return url === GRID_URL;
    }, 10000);
  },
  async afterAll() {
    await closeBrowser();
  },
  async beforeEach() {
    setConfig({
      retryInterval: 100,
      retryTimeout: 30000,
      navigationTimeout: 40000,
      ignoreSSLErrors: true,
    });
    await openIncognitoWindow(GRID_URL, {
      name: 'admin',
      waitForNavigation: true,
    });
    await video.startRecording('output/video.mp4');
  },
  async afterEach() {
    if (this.currentTest.state !== 'passed') {
      await screenshot({
        path: `${screenShotPath}/${this.currentTest.title.replace(/ /g, '_')}.png`,
      });
    }
    await video.stopRecording();
    await clearIntercept();
    await closeIncognitoWindow();
  },
};

```

**Comment by saikrishna321** [comment]
@hkang1 Any help here please?

**Comment by saikrishna321** [comment]
@hkang1 Can you please make a release with the fix.
